/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
          950: '#431407',
        },
        secondary: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
          950: '#450a0a',
        },
        accent: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
          950: '#451a03',
        },
        dark: {
          50: '#0a0a0a',
          100: '#0d0d0d',
          200: '#111111',
          300: '#141414',
          400: '#1a1a1a',
          500: '#1f1f1f',
          600: '#2a2a2a',
          700: '#333333',
          800: '#404040',
          900: '#505050',
          950: '#050505',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Poppins', 'system-ui', 'sans-serif'],
      },
      animation: {
        'gradient': 'gradient 8s ease infinite',
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 3s infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'fade-in': 'fadeIn 0.5s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'bounce-gentle': 'bounceGentle 2s ease-in-out infinite',
        'glow-pulse': 'glowPulse 3s ease-in-out infinite',
        'drift': 'drift 20s ease-in-out infinite',
        'shimmer-fast': 'shimmer 1.5s linear infinite',
        'ember': 'ember 3s ease-in infinite',
        'ember-slow': 'ember 5s ease-in infinite',
        'aurora': 'aurora 10s ease-in-out infinite alternate',
        'aurora-slow': 'aurora 15s ease-in-out infinite alternate',
        'spark': 'spark 2s ease-out infinite',
        'spark-drift': 'sparkDrift 8s ease-in-out infinite',
        'mesh-glow': 'meshGlow 8s ease-in-out infinite alternate',
        'float-particle': 'floatParticle 12s ease-in-out infinite',
      },
      keyframes: {
        gradient: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 5px rgba(249, 115, 22, 0.3), 0 0 20px rgba(249, 115, 22, 0.1)' },
          '50%': { boxShadow: '0 0 20px rgba(249, 115, 22, 0.5), 0 0 40px rgba(249, 115, 22, 0.2)' },
        },
        bounceGentle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        glowPulse: {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        },
        drift: {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
          '25%': { transform: 'translate(10px, -10px) rotate(5deg)' },
          '50%': { transform: 'translate(-5px, -15px) rotate(-3deg)' },
          '75%': { transform: 'translate(-10px, 5px) rotate(4deg)' },
        },
        ember: {
          '0%': { transform: 'translateY(0) scale(1)', opacity: '1' },
          '100%': { transform: 'translateY(-100vh) scale(0)', opacity: '0' },
        },
        aurora: {
          '0%': { transform: 'translateX(-10%) translateY(-5%) rotate(0deg)', opacity: '0.3' },
          '50%': { transform: 'translateX(5%) translateY(5%) rotate(5deg)', opacity: '0.5' },
          '100%': { transform: 'translateX(10%) translateY(-10%) rotate(-5deg)', opacity: '0.3' },
        },
        spark: {
          '0%': { transform: 'scale(1) translateY(0)', opacity: '1' },
          '100%': { transform: 'scale(0) translateY(-30px)', opacity: '0' },
        },
        sparkDrift: {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
          '33%': { transform: 'translate(20px, -15px) rotate(10deg)' },
          '66%': { transform: 'translate(-15px, -25px) rotate(-8deg)' },
        },
        meshGlow: {
          '0%': { transform: 'translate(0, 0) scale(1)', opacity: '0.15' },
          '33%': { transform: 'translate(30px, -20px) scale(1.1)', opacity: '0.2' },
          '66%': { transform: 'translate(-20px, 15px) scale(0.9)', opacity: '0.1' },
          '100%': { transform: 'translate(10px, -10px) scale(1.05)', opacity: '0.15' },
        },
        floatParticle: {
          '0%, 100%': { transform: 'translateY(0) translateX(0)' },
          '25%': { transform: 'translateY(-20px) translateX(10px)' },
          '50%': { transform: 'translateY(-10px) translateX(-15px)' },
          '75%': { transform: 'translateY(-30px) translateX(5px)' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
};
